.TH "lcscan-backend" "7" "0.3r3" "Pozsar Zsolt" "Logical circuit scanner"
.SH "NAME"
.LP 
LCScan - Logical circuit scanner
.SH "SYNTAX"
.LP
lcscan-backend
.br
.SH "DESCRIPTION"
.LP 
  This file is a part of LCScan for internal use only. Do no run it manually.
.SH "AUTHOR"
.LP 
Pozsar Zsolt
.br
Web:    http://www.pozsarzs.hu
.br
E-mail and MSN:   pozsarzs@gmail.com
