.TH "lcscan" "7" "0.3r3" "Pozsár Zsolt" "Logikai áramkör szkenner"
.SH "NÉV"
.LP 
LCScan - Logikai áramkör szkenner
.SH "ÁTTEKINTÉS"
.LP
.br
lcscan
.br
.SH "LEÍRÁS"
.LP 
  Az LCScan egy statikus logikai hálózatokhoz használható áramkör
szkenner. Az illesztő egység a párhuzamos portra csatlakozik. Nyolc TTL
szintű kimenettel és nyolc túlfeszültségvédett, Schmitt-triggeres
bemenettel rendelkezik.
.SH "ÁLLOMÁNYOK"
.LP 
\fI/opt/lcscan/document/hardware/*\fP
.br
  Az illesztő teljes dokumentációja (kapcsolási rajzok, nyák rajz, stb.)
.SH "KÖRNYEZETI VÁLTOZÓK"
.LP 
\fBLANG\fP
.br
  Evvel a környezeti változóval állíthatjuk be a program nyelvét. Ha ez
egy nem támogatott nyelv, akkor a feliratok angol nyelvűek lesznek.
Alak: hu, hu_HU.
Jelenleg elérhető nyelvek: angol, magyar.
.SH "SZERZŐ"
.LP 
Pozsár Zsolt
.br
Web:    http://www.pozsarzs.hu
.br
E-mail and MSN:   pozsarzs@gmail.com
