.TH "lcscan" "7" "0.3r3" "Pozsar Zsolt" "Logical circuit scanner"
.SH "NAME"
.LP 
LCScan - Logical circuit scanner
.SH "SYNTAX"
.LP
lcscan
.br
.SH "DESCRIPTION"
.LP 
  LCScan is an circuit scanner for static logical network. Interface
connects to paralel port. It has eight TTL level outputs and eight
overload-protected, Schmitt-trigger inputs.
.SH "FILES"
.LP 
\fI/opt/lcscan/document/hardware/*\fP
.br
  Full documentation of interface. (schematic draws, pcb draw, etc.)
.SH "ENVIRONMENTAL VARIABLES"
.LP 
\fBLANG\fP
.br
  You can set language of labels with these variables.
If it is a non-supported language, text will be English.
Format: en, en_EN.
Available language are English and Hungarian.
.SH "AUTHOR"
.LP 
Pozsar Zsolt
.br
Web:    http://www.pozsarzs.hu
.br
E-mail and MSN:   pozsarzs@gmail.com
