.TH "lcscan-backend" "7" "0.3r3" "Pozsár Zsolt" "Logikai áramkör szkenner"
.SH "NÉV"
.LP 
LCScan - Logikai áramkör szkenner
.SH "ÁTTEKINTÉS"
.LP
.br
lcscan-backend
.br
.SH "LEÍRÁS"
.LP 
  Ez a fájl az LCScan része, kizárólag 'belső' használatra. Ne futtassa!
.SH "SZERZŐ"
.LP 
Pozsár Zsolt
.br
Web:    http://www.pozsarzs.hu
.br
E-mail and MSN:   pozsarzs@gmail.com
